In [1]:
import tensorflow as tf
import keras 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

ImportError: Traceback (most recent call last):
  File "/home/nj/anaconda3/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/nj/anaconda3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/nj/anaconda3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/home/nj/anaconda3/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/nj/anaconda3/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

In [2]:
dataset = pd.read_csv("Churn_Modelling.csv")
# Last row tells us if the person has left the bank or not

In [3]:
dataset.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X=dataset.iloc[:,3:13].values
X[0:5]

array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1]], dtype=object)

In [5]:
y=dataset.iloc[:,13].values
y[0:5]

array([1, 0, 1, 0, 0])

In [6]:
# Encoding for country and gender
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
encoder_x1=LabelEncoder()
X[:,1]=encoder_x1.fit_transform(X[:,1])
encoder_x2=LabelEncoder()
X[:,2]=encoder_x2.fit_transform(X[:,2])
X[0:5]

array([[619, 0, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 2, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 0, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 0, 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 2, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1]], dtype=object)

In [7]:
np.set_printoptions(suppress=True)

In [8]:
# One hot encoding for 3 countries (0,1,2)
onehot_x=OneHotEncoder(categorical_features=[1])
X=onehot_x.fit_transform(X).toarray()
X=X[:,1:]

In [9]:
X[5]

array([      0.  ,       1.  ,     645.  ,       1.  ,      44.  ,
             8.  ,  113755.78,       2.  ,       1.  ,       0.  ,
        149756.71])

In [10]:
# Split train and test datalables
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=7)

In [11]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)


In [12]:
?keras

In [18]:
from keras.models import Sequential
from keras.layers import Dense
from keras.objectives import categorical_crossentropy
from keras.objectives import binary_crossentropy
#from keras import losses


# Create a model with 2 hidden layer and 1 output layer
model = Sequential()
model.add(Dense(output_dim=6,input_dim=11,activation='relu',init='uniform'))
model.add(Dense(output_dim=6,activation='relu',init='uniform'))
model.add(Dense(output_dim=1,activation='sigmoid',init='uniform'))


#Complie and fit
model.compile(optimizer='adam',loss='mean_squared_error',metrics=['accuracy'])
model.fit(X_train,y_train,batch_size=32,nb_epoch=10)


Epoch 1/10
8000/8000 [==============================] - 25s - loss: 0.1969 - acc: 0.7966    
Epoch 2/10
8000/8000 [==============================] - 0s - loss: 0.1399 - acc: 0.7967     
Epoch 3/10
8000/8000 [==============================] - 0s - loss: 0.1371 - acc: 0.7967     
Epoch 4/10
8000/8000 [==============================] - 0s - loss: 0.1353 - acc: 0.7967     
Epoch 5/10
8000/8000 [==============================] - 0s - loss: 0.1339 - acc: 0.7967     
Epoch 6/10
8000/8000 [==============================] - 0s - loss: 0.1322 - acc: 0.7967     
Epoch 7/10
8000/8000 [==============================] - 0s - loss: 0.1310 - acc: 0.8183     
Epoch 8/10
8000/8000 [==============================] - 0s - loss: 0.1301 - acc: 0.8284     
Epoch 9/10
8000/8000 [==============================] - 0s - loss: 0.1294 - acc: 0.8314     
Epoch 10/10
8000/8000 [==============================] - 0s - loss: 0.1287 - acc: 0.8335     


In [19]:
# Predict on test data
y_pred=model.predict(X_test)
y_pred=(y_pred>0.5)

In [20]:
# Confustion matrix: to check accuracy and false positives
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [21]:
cm

array([[1547,   42],
       [ 304,  107]])

In [36]:
# new data
# Note: You should transform the data before adding here: sc.transform()
new_pred=model.predict(sc.transform(np.array([[0.0,0,60,1,40,3,6000,2,1,1,50000]])))
new_pred=(new_pred>0.5)

In [37]:
new_pred

array([[False]], dtype=bool)

In [28]:
# False means: Customer doesn't leave the bank


In [ ]:
#619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88